# General Settings
seed: 420
checkpoint: 

# Model
optimiser_type: adam_w  # AdamW optimizer
lr: 5.0e-5  
weight_decay: 1.0e-4
lr_schedulers_type: plateau
differential_lr: False
differential_lr_scaling: 0.1

# LiDAR Point Cloud Range & Voxelization
x_range: [ -5, 5 ]  # x-range for the LiDAR point cloud (ensure objects are within this range)
y_range: [ -5, 5 ]  # y-range for the LiDAR point cloud
z_range: [ -3, 3 ]  # Narrowing down the z-range for more relevant vertical data (usually -3 to 3 meters)
voxel_size: 0.02  # Decrease voxel size for higher granularity (should improve BEV resolution)
num_queries: 45  # Number of object queries for Mask_bev

# Head Settings (Adjusting for better performance)
head_reverse_class_weights: False  # Enable reverse class weights if class imbalance is an issue

# Encoder Settings
max_num_points: 32  # Number of points to sample per voxel (increased from default to capture more details)
encoder_feat_channels: [128, 128, 128]  # Feature channels for the encoder, keeping it consistent
head_feat_channels: 256
head_out_channels: 256

# Backbone Settings
backbone_embed_dim: 192  # Embedding dimensions for the backbone
backbone_use_abs_emb: False  # Use absolute positional embeddings (disable to avoid overfitting)

# Dataset Settings
dataset: kitti  # Ensure dataset is set to KITTI
batch_size: 4
num_workers: 8  # Keep this for optimal data loading (adjust based on system resources)
pin_memory: True
remove_unseen: True  # Remove unseen data points from the training process to improve generalization
shuffle_train: True  # Shuffle training data for better convergence
min_num_points: 1  # Minimum number of points to consider when training on objects

augmentations:
  - name: 'object_sample'
    dataset_root: 'data/KITTI'
    num_sample: 15
  - name: 'object_noise'
  - name: 'flip'
    prob_flip_x: 0
    prob_flip_y: 0.5
  - name: 'rotate'
    rotate_prob: 0.1
    rotation_range: 2.5
  - name: 'global_noise'
    prob_aug: 0.5
  - name: 'drop'
    prob_drop: 0.1
    per_point_drop_prob: 0.05
  - name: 'shuffle'
    prob_shuffle: 0.5
  - name: 'jitter'
    prob_jitter: 0.25
    jitter_std: 0.01
    intensity_std: 0.01

